/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 js.gltf js.jsx 
Author: agustin.trezza (https://sketchfab.com/agustin.trezza)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/javascript-1-e6a5af39d2b3495fb4fb1f8f94d3efda
Title: Javascript (1)
*/
/*eslint-disable */
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";


export default function Js(props) {
  const { nodes, materials } = useGLTF("/js.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.mat_3220964}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/js.gltf");
